name: C_C++_CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - ninja-build

jobs:
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@ninja-build
    with: 
      dependencies: 'ninja gcc gcovr cmake openmpi boost'
      clang-build: false
      gcc-build: true
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  # build-with-clang:
  #   uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@master
  #   with: 
  #     dependencies: 'clang gcovr cmake openmpi boost'
  #     clang-build: true
  #     gcc-build: false
  #   secrets:
  #     CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
