name: Lint Master
on:
  push:
    branches:
      - master

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get clang-format-9
        run: .github/workflows/scripts/get_dependencies.sh clang_format
      - name: Lint
        run: .github/workflows/scripts/lint.sh sde
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
